# Generated by Django 5.2 on 2025-04-03 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KindTU',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('is_for_journal', models.BooleanField(default=False, verbose_name='Для журнала')),
            ],
            options={
                'verbose_name': 'Вид ТУ',
                'verbose_name_plural': 'Виды ТУ',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('country', models.CharField(blank=True, max_length=200, null=True, verbose_name='Страна-производитель')),
            ],
            options={
                'verbose_name': 'Завод-изготовитель',
                'verbose_name_plural': 'Заводы-изготовители',
            },
        ),
        migrations.CreateModel(
            name='NameTU',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Название ТУ',
                'verbose_name_plural': 'Названия ТУ',
            },
        ),
        migrations.CreateModel(
            name='TypeTU',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('is_for_journal', models.BooleanField(default=False, verbose_name='Для журнала')),
            ],
            options={
                'verbose_name': 'Тип ТУ',
                'verbose_name_plural': 'Типы ТУ',
            },
        ),
        migrations.CreateModel(
            name='TU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Регистрационный номер оборудования')),
                ('serial_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Серийный номер')),
                ('state_registration_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Гос. регистрационный номер')),
                ('factory_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заводской номер')),
                ('brand', models.CharField(blank=True, max_length=500, null=True, verbose_name='Марка')),
                ('technical_characteristics', models.CharField(blank=True, max_length=200, null=True, verbose_name='Краткие тех. характеристики')),
                ('gtt_registration_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Регистрационный номер ГТТ')),
                ('scheme_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер по тех. схеме')),
                ('manufacture_year', models.CharField(blank=True, max_length=200, null=True, verbose_name='Год изготовления')),
                ('service_life_years', models.SmallIntegerField(blank=True, null=True, verbose_name='Нормативный срок эксплуатации (лет)')),
                ('commissioning_year', models.SmallIntegerField(blank=True, null=True, verbose_name='Год ввода в эксплуатацию')),
                ('decommissioning_year', models.SmallIntegerField(blank=True, null=True, verbose_name='Год окончания эксплуатации')),
                ('wear_percentage', models.FloatField(blank=True, null=True, verbose_name='Процент износа')),
                ('last_epb_date', models.DateField(blank=True, null=True, verbose_name='Дата последнего ЭПБ')),
                ('next_epb_date', models.DateField(blank=True, null=True, verbose_name='Дата следующего ЭПБ')),
                ('last_inspection_date', models.DateField(blank=True, null=True, verbose_name='Дата очередной проверки')),
                ('next_inspection_date', models.DateField(blank=True, null=True, verbose_name='Дата следующей проверки')),
                ('permitted_service_life', models.SmallIntegerField(blank=True, null=True, verbose_name='Разрешённый срок эксплуатации')),
                ('has_safety_device', models.BooleanField(blank=True, null=True, verbose_name='Наличие предохранительного устройства')),
                ('safety_device_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Тип предохранительного устройства')),
                ('volume_m3', models.FloatField(blank=True, null=True, verbose_name='Объём (м³)')),
                ('object_pressure_mpa', models.FloatField(blank=True, null=True, verbose_name='Объектное давление (МПа)')),
                ('dy_mm', models.FloatField(blank=True, null=True, verbose_name='Диаметр (мм)')),
                ('type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Тип')),
                ('subtype', models.CharField(blank=True, max_length=200, null=True, verbose_name='Подтип')),
                ('lifting_capacity_t', models.FloatField(blank=True, null=True, verbose_name='Грузоподъёмность (т)')),
                ('volume_t', models.FloatField(blank=True, null=True, verbose_name='Объём (т)')),
                ('equipment_pressure_mpa', models.FloatField(blank=True, null=True, verbose_name='Давление оборудования (МПа)')),
                ('modernization_year', models.SmallIntegerField(blank=True, null=True, verbose_name='Год модернизации')),
                ('completed_measures', models.CharField(blank=True, max_length=200, null=True, verbose_name='Проведённые мероприятия')),
                ('rtn_permission_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер разрешения РТН')),
                ('epb_conclusion_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер заключения ЭПБ')),
                ('passport_present', models.BooleanField(blank=True, null=True, verbose_name='Наличие паспорта')),
                ('opo_info', models.CharField(blank=True, max_length=200, null=True, verbose_name='Сведения об ОПО')),
                ('rtn_info', models.BooleanField(blank=True, null=True, verbose_name='Информация РТН')),
                ('compliance_certificate_present', models.BooleanField(blank=True, null=True, verbose_name='Наличие сертификата соответствия')),
                ('rtn_certificate_present', models.BooleanField(blank=True, null=True, verbose_name='Наличие сертификата РТН')),
                ('manufacturer_country', models.CharField(blank=True, max_length=200, null=True, verbose_name='Страна-производитель')),
                ('manufacturer_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Завод-изготовитель')),
                ('epb_conclusion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Вывод ЭПБ')),
                ('total_cycles', models.IntegerField(blank=True, null=True, verbose_name='Количество циклов')),
                ('actual_cycles', models.IntegerField(blank=True, null=True, verbose_name='Фактическое количество циклов')),
                ('replacement_id', models.IntegerField(blank=True, null=True, verbose_name='ID замены')),
                ('replacement_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер замены')),
                ('note1', models.TextField(blank=True, null=True, verbose_name='Примечание 1')),
                ('note2', models.TextField(blank=True, null=True, verbose_name='Примечание 2')),
                ('note3', models.TextField(blank=True, null=True, verbose_name='Примечание 3')),
                ('sr_control_presence_id', models.IntegerField(blank=True, null=True, verbose_name='ID наличия СР контроля')),
                ('cb_oncontrol', models.BooleanField(default=0, verbose_name='На контроле')),
                ('date_updated', models.DateTimeField(blank=True, null=True, verbose_name='Дата обновления')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Обновлено пользователем')),
                ('is_deleted', models.BooleanField(default=0, verbose_name='Удалено')),
                ('device_name_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.nametu', verbose_name='ID наименования устройства')),
                ('hazard_class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='opo.hazardclass', verbose_name='ID класса опасности')),
                ('kind_device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.kindtu', verbose_name='ID вида устройства')),
                ('manufacturer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.manufacturer', verbose_name='ID завода-изготовителя')),
                ('opo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opo.opo', verbose_name='ID ОПО')),
                ('device_type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.typetu', verbose_name='ID типа устройства')),
            ],
            options={
                'verbose_name': 'Техническое устройство',
                'verbose_name_plural': 'Технические устройства',
            },
        ),
        migrations.CreateModel(
            name='ControlNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_card_number', models.IntegerField(blank=True, null=True, verbose_name='Номер карты пользователя')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст заметки')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
                ('tu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.tu', verbose_name='ID технического устройства')),
            ],
            options={
                'verbose_name': 'Заметка контроля',
                'verbose_name_plural': 'Заметки контроля',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=500, verbose_name='Тип сертификата')),
                ('number', models.CharField(max_length=200, verbose_name='Номер сертификата')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('issued_by', models.CharField(max_length=500, verbose_name='Кем выдано')),
                ('scan', models.BinaryField(blank=True, null=True, verbose_name='Скан-копия')),
                ('tu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.tu', verbose_name='ID ТУ')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
    ]
