# Generated by Django 5.2 on 2025-04-03 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HazardClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Класс опасности',
                'verbose_name_plural': 'Классы опасности',
            },
        ),
        migrations.CreateModel(
            name='TypeOPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('short_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Краткое название')),
                ('reg_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Регистрационный номер')),
            ],
            options={
                'verbose_name': 'Тип ОПО',
                'verbose_name_plural': 'Типы ОПО',
            },
        ),
        migrations.CreateModel(
            name='OPO',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID ОПО')),
                ('structural_unit', models.IntegerField(verbose_name='ID структурного подразделения')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('short_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Краткое название')),
                ('reg_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Регистрационный номер')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opo.typeopo', verbose_name='ID типа ОПО')),
            ],
            options={
                'verbose_name': 'ОПО',
                'verbose_name_plural': 'ОПО',
            },
        ),
    ]
